### PR TITLE
Update common.json

### PR DESCRIPTION
**Pull request by XUSDP**
I started translation I should finish it tomorrow I'm not very familiar with GitHub. RJeo

### CODE REVIEW

**Comment by joeblau** [comment]
@XUSDP I think you're updating the "en/common.json" file, when should be updating the `es/common.json`. Outside of that it looks good!

**Comment by XUSDP** [comment]
Thank you. I am going to if can finish it later today

**Comment by XUSDP** [comment]
Can you send me the link for es/common.json

**Comment by joeblau** [comment]
It's right here: https://github.com/atomizexyz/xenfyi/tree/main/public/locales/es/common.json

**Comment by joeblau** [comment]
@XUSDP — I'm going to close this out, I've merged your changes into the main in the es/common.json. You can keep working out of that folder. Once all of the translations are complete, I'll update the site to be in Spanish.

**Pull request closed without merging**
