### PR TITLE
Update common.json

### PR DESCRIPTION
**Pull request by iamgoonin**
Sup bro. Here's the Tagalog (Filipino Language) version.

### CODE REVIEW

**Comment by joeblau** [comment]
can move move this out of the `en` directory and make a `tl` directory?

**Comment by joeblau** [comment]
You've gotta keep the original common.json — that's the English translation. Here lets close this and I'll give you a template to setup from.

**Comment by iamgoonin** [comment]
> 

I think I'm making this more complicated than it is. ok.

**Comment by joeblau** [comment]
Ah you fixed it in the other one

**Comment by iamgoonin** [comment]
> Ah you fixed it in the other one

so ignore this pull request now?

**Pull request closed without merging**
